
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueServer", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueServer {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversioneutotoDh", targetNamespace = "http://WS/", className = "proxy.ConversioneutotoDh")
    @ResponseWrapper(localName = "conversioneutotoDhResponse", targetNamespace = "http://WS/", className = "proxy.ConversioneutotoDhResponse")
    @Action(input = "http://WS/BanqueServer/conversioneutotoDhRequest", output = "http://WS/BanqueServer/conversioneutotoDhResponse")
    public double conversioneutotoDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://WS/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://WS/", className = "proxy.GetcompteResponse")
    @Action(input = "http://WS/BanqueServer/getcompteRequest", output = "http://WS/BanqueServer/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listcompte", targetNamespace = "http://WS/", className = "proxy.Listcompte")
    @ResponseWrapper(localName = "listcompteResponse", targetNamespace = "http://WS/", className = "proxy.ListcompteResponse")
    @Action(input = "http://WS/BanqueServer/listcompteRequest", output = "http://WS/BanqueServer/listcompteResponse")
    public List<Compte> listcompte();

}
